"use strict";

/**
 * Receipts Module (Phase 5)
 * Handles professional A4 PDF receipt generation.
 */

/* global jspdf */

var BK = window.BK || {};

(function () {
  var U = BK.Utils;

  BK.Receipts = {
    generateA4: function (txn) {
      if (!txn) return;
      
      var self = this;
      this.getBusinessDetails().then(function(biz) {
        self.renderPDF(txn, biz);
      });
    },

    getBusinessDetails: function() {
      return BK.db.preferences.toArray().then(function(prefs) {
        var biz = {};
        prefs.forEach(function(p) {
          if (p.key === 'biz_name') biz.name = p.value;
          if (p.key === 'biz_address') biz.address = p.value;
          if (p.key === 'biz_phone') biz.phone = p.value;
          if (p.key === 'biz_logo') biz.logo = p.value;
        });
        return biz;
      });
    },

    renderPDF: function (txn, biz) {
      var JsPDF = jspdf.jsPDF;
      var doc = new JsPDF('p', 'pt', 'a4');
      
      var margin = 40;
      var pageWidth = doc.internal.pageSize.getWidth();
      var accentColor = [0, 0, 0]; // Ink
      
      // ─── Header ───
      // Logo
      if (biz.logo) {
        try {
          doc.addImage(biz.logo, 'PNG', margin, margin, 60, 60);
        } catch(e) { console.error('Logo failed to render', e); }
      }

      // Business Info
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.text(biz.name || 'Bank Bookkeeper', biz.logo ? 110 : margin, margin + 20);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(100);
      var sublineY = margin + 35;
      if (biz.address) {
        doc.text(biz.address, biz.logo ? 110 : margin, sublineY);
        sublineY += 14;
      }
      if (biz.phone) {
        doc.text('Phone: ' + biz.phone, biz.logo ? 110 : margin, sublineY);
      }

      // Receipt Title & ID
      doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.setLineWidth(2);
      doc.line(margin, 120, pageWidth - margin, 120);

      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text('TRANSACTION RECEIPT', margin, 145);
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text('Receipt No: #' + (txn.id + 1000), pageWidth - margin, 145, { align: 'right' });

      // ─── Body ───
      var startY = 180;
      var rowHeight = 30;

      function renderRow(label, value, y, isBoldValue) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(120);
        doc.text(label, margin, y);
        
        doc.setFont('helvetica', isBoldValue ? 'bold' : 'normal');
        doc.setTextColor(0);
        doc.text(String(value), 180, y);
        
        doc.setDrawColor(240);
        doc.setLineWidth(0.5);
        doc.line(margin, y + 8, pageWidth - margin, y + 8);
      }

      renderRow('Date', U.formatDate(txn.date), startY);
      renderRow('Type', txn.type.toUpperCase(), startY + rowHeight);
      
      doc.setFontSize(14);
      renderRow('Amount', U.formatCurrency(txn.amount), startY + rowHeight * 2, true);
      doc.setFontSize(10);
      
      renderRow('Description', txn.description || 'N/A', startY + rowHeight * 3);
      
      // ─── Total Box ───
      var boxY = startY + rowHeight * 5;
      doc.setFillColor(250, 251, 255);
      doc.rect(margin, boxY, pageWidth - margin * 2, 80, 'F');
      doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.rect(margin, boxY, pageWidth - margin * 2, 80, 'S');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('TOTAL AMOUNT', margin + 20, boxY + 35);
      
      doc.setFontSize(24);
      doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.text(U.formatCurrency(txn.amount), pageWidth - margin - 20, boxY + 50, { align: 'right' });

      // ─── Footer ───
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text('Thank you for using our bookkeeping services.', pageWidth / 2, 750, { align: 'center' });
      doc.text('This is a computer-generated document and requires no signature.', pageWidth / 2, 765, { align: 'center' });
      
      doc.setDrawColor(230);
      doc.line(margin, 780, pageWidth - margin, 780);
      doc.text('Generated by Bank Bookkeeper Pro', margin, 795);
      doc.text(new Date().toLocaleString(), pageWidth - margin, 795, { align: 'right' });

      doc.save('Receipt_' + txn.id + '_' + txn.date + '.pdf');
      BK.Toast.success('A4 Receipt generated successfully.');
    }
  };
})();
