"use strict";

/**
 * Receipts Module (Phase 5)
 * Handles professional A4 PDF receipt generation.
 */

/* global jspdf */

var BK = window.BK || {};

(function () {
  var U = BK.Utils;

  BK.Receipts = {
    generateA4: function (txn) {
      if (!txn) return;
      
      var self = this;
      this.getBusinessDetails().then(function(biz) {
        self.renderPDF(txn, biz);
      });
    },

    getBusinessDetails: function() {
      return BK.db.preferences.toArray().then(function(prefs) {
        var biz = {};
        prefs.forEach(function(p) {
          if (p.key === 'biz_name') biz.name = p.value;
          if (p.key === 'biz_address') biz.address = p.value;
          if (p.key === 'biz_phone') biz.phone = p.value;
          if (p.key === 'biz_logo') biz.logo = p.value;
        });
        return biz;
      });
    },

    renderPDF: function (txn, biz) {
      var JsPDF = jspdf.jsPDF;
      var doc = new JsPDF('p', 'pt', 'a4');
      
      var margin = 40;
      var pageWidth = doc.internal.pageSize.getWidth();
      var accentColor = [0, 0, 0]; // Ink
      
      // ─── Header ───
      // Logo
      if (biz.logo) {
        try {
          doc.addImage(biz.logo, 'PNG', margin, margin, 60, 60);
        } catch(e) { console.error('Logo failed to render', e); }
      }

      // Business Info
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.text(biz.name || 'Bank Bookkeeper', biz.logo ? 110 : margin, margin + 20);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(100);
      var sublineY = margin + 35;
      if (biz.address) {
        doc.text(biz.address, biz.logo ? 110 : margin, sublineY);
        sublineY += 14;
      }
      if (biz.phone) {
        doc.text('Phone: ' + biz.phone, biz.logo ? 110 : margin, sublineY);
      }

      // Receipt Title & ID
      doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.setLineWidth(2);
      doc.line(margin, 120, pageWidth - margin, 120);

      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text('TRANSACTION RECEIPT', margin, 145);
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text('Receipt No: #' + (txn.id + 1000), pageWidth - margin, 145, { align: 'right' });

      // ─── Body ───
      var startY = 180;
      var rowHeight = 30;

      function renderRow(label, value, y, isBoldValue) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(120);
        doc.text(label, margin, y);
        
        doc.setFont('helvetica', isBoldValue ? 'bold' : 'normal');
        doc.setTextColor(0);
        doc.text(String(value), 180, y);
        
        doc.setDrawColor(240);
        doc.setLineWidth(0.5);
        doc.line(margin, y + 8, pageWidth - margin, y + 8);
      }

      renderRow('Date', U.formatDate(txn.date), startY);
      renderRow('Type', txn.type.toUpperCase(), startY + rowHeight);
      
      doc.setFontSize(14);
      renderRow('Amount', U.formatCurrency(txn.amount), startY + rowHeight * 2, true);
      doc.setFontSize(10);
      
      renderRow('Description', txn.description || 'N/A', startY + rowHeight * 3);
      
      // ─── Total Box ───
      var boxY = startY + rowHeight * 5;
      doc.setFillColor(250, 251, 255);
      doc.rect(margin, boxY, pageWidth - margin * 2, 80, 'F');
      doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.rect(margin, boxY, pageWidth - margin * 2, 80, 'S');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('TOTAL AMOUNT', margin + 20, boxY + 35);
      
      doc.setFontSize(24);
      doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.text(U.formatCurrency(txn.amount), pageWidth - margin - 20, boxY + 50, { align: 'right' });

      // ─── Footer ───
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text('Thank you for using our bookkeeping services.', pageWidth / 2, 750, { align: 'center' });
      doc.text('This is a computer-generated document and requires no signature.', pageWidth / 2, 765, { align: 'center' });
      
      doc.setDrawColor(230);
      doc.line(margin, 780, pageWidth - margin, 780);
      doc.text('Generated by Bank Bookkeeper Pro', margin, 795);
      doc.text(new Date().toLocaleString(), pageWidth - margin, 795, { align: 'right' });

      doc.save('Receipt_' + txn.id + '_' + txn.date + '.pdf');
      BK.Toast.success('A4 Receipt generated successfully.');
    }
  };

  /**
   * Receipts Vault Controller
   * Renders the gallery of attached receipts
   */
  function ReceiptsVaultController() {}

  ReceiptsVaultController.prototype.render = function () {
    var gallery = document.getElementById('receipts-gallery');
    if (!gallery) return;

    U.clearChildren(gallery);

    BK.TransactionsDB.getAll().then(function (txns) {
      var receiptTxns = txns.filter(function (t) { return t.receiptData; });

      if (receiptTxns.length === 0) {
        gallery.style.display = 'block';
        gallery.appendChild(U.createElement('div', { 
          className: 'table-empty', 
          style: { padding: '60px 20px' } 
        }, [
          U.createElement('i', { className: 'fas fa-image', style: { fontSize: '48px', color: 'var(--primary)', opacity: '0.4' } }),
          U.createElement('p', { style: { fontWeight: '600', fontSize: '18px', marginTop: '16px' } }, ['No Receipts Found']),
          U.createElement('p', { style: { color: 'var(--text-secondary)' } }, ['Attach images or PDFs to your transactions to see them here.'])
        ]));
        return;
      }

      gallery.style.display = 'grid';

      receiptTxns.forEach(function (txn) {
        var isImg = txn.receiptType && txn.receiptType.startsWith('image/');
        
        var preview = isImg ? U.createElement('img', { 
          src: txn.receiptData, 
          style: { width: '100%', height: '160px', objectFit: 'cover', borderTopLeftRadius: 'var(--radius-lg)', borderTopRightRadius: 'var(--radius-lg)' } 
        }) : U.createElement('div', { 
          style: { width: '100%', height: '160px', background: 'var(--bg-secondary)', display: 'flex', alignItems: 'center', justifyContent: 'center', borderTopLeftRadius: 'var(--radius-lg)', borderTopRightRadius: 'var(--radius-lg)' } 
        }, [
          U.createElement('i', { className: 'fas fa-file-pdf', style: { fontSize: '48px', color: 'var(--danger)' } })
        ]);

        var card = U.createElement('div', { 
          className: 'card', 
          style: { padding: '0', cursor: 'pointer', transition: 'transform 0.2s', overflow: 'hidden' },
          onClick: function () {
            if (isImg) {
              var w = window.open("");
              w.document.write('<img src="' + txn.receiptData + '" style="max-width:100%;">');
            } else {
              var pdfWindow = window.open("");
              pdfWindow.document.write('<iframe width="100%" height="100%" src="' + txn.receiptData + '"></iframe>');
            }
          }
        }, [
          preview,
          U.createElement('div', { style: { padding: '16px' } }, [
            U.createElement('div', { style: { fontWeight: '600', fontSize: '16px', marginBottom: '4px' } }, [U.formatCurrency(txn.amount)]),
            U.createElement('div', { style: { fontSize: '13px', color: 'var(--text-secondary)', marginBottom: '8px' } }, [U.formatDate(txn.date)]),
            U.createElement('div', { style: { fontSize: '14px', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' } }, [txn.description || 'No Description'])
          ])
        ]);
        
        card.onmouseover = function() { card.style.transform = 'translateY(-4px)'; card.style.boxShadow = 'var(--shadow-md)'; };
        card.onmouseout = function() { card.style.transform = 'none'; card.style.boxShadow = 'var(--shadow-sm)'; };
        
        gallery.appendChild(card);
      });
    });
  };

  BK.ReceiptsVaultController = ReceiptsVaultController;
})();
